index.d.ts
I did a dumdum and used interfaces for everything. Switched to classes
=> fix typings and add private methods

index.d.ts
I realized I needed to get all of it exported lol.
=> typings: Export all types

index.d.ts
please someone remember to update the typings
=> chore: add start event to typings

src/Shoukaku.js, src/guild/ShoukakuLink.js, src/guild/ShoukakuPlayer.js, src/node/ShoukakuSocket.js
This will add support for Lavalink Filters and also contains various quality of life changes and bug fixes
This is a re-created PR as the old one was accidentally closed
Before reporting an issue, please make sure you uninstall then re-install the library to ensure you have the latest commit
Progress:
To hop in the testing train just do
```
npm install git://github.com/Deivu/Shoukaku.git#filters --save
```
For feedback and issues with it, just comment in this thread.
=> Lavalink Filters

index.d.ts
This PR improves the typings especially in ShoukakuPlayer (added typings for the events) and some fixes
=> improve typings

index.d.ts, src/constants/ShoukakuConstants.js, src/guild/ShoukakuPlayer.js
- implement pause option for ShoukakuPlayer#playTrack
- added connected field on PlayerUpdateEvent#state
- typings and typo fix
=> some implementations and fixes

index.d.ts
The typescript types that reference data IDs have been updated to the new data types that discord.js incorporates.
=> Fixed Id type error with the new version of discord.js#master

LICENSE
Nothing just updating the license year....................
=> chore: bump license year

README.md, package.json
There is no use of djs-light now cuz v13 of djs has cache control in built
So this pr removes the package
=> Removes discord.js-light from package.json

types/Constants.d.ts, types/Shoukaku.d.ts, types/guild/ShoukakuConnection.d.ts, types/guild/ShoukakuPlayer.d.ts, types/libraries/Libraries.d.ts, types/libraries/wrappers/DiscordJS.d.ts, types/libraries/wrappers/Eris.d.ts, types/node/ShoukakuRest.d.ts, types/node/ShoukakuSocket.d.ts, types/struct/ShoukakuFilter.d.ts, types/struct/ShoukakuStats.d.ts
I have fixed a few typings and have added some
=> Typings again

types/Constants.d.ts, types/Shoukaku.d.ts, types/guild/ShoukakuConnection.d.ts, types/node/ShoukakuSocket.d.ts
=> fix types for snowflake

types/index.d.ts
imp sure every playerupdate event has a conected boolean, which is not specified in the types
=> types: add connected boolean in playerupdate

types/index.d.ts
=> feat(types): change PlayerUpdate.state.position to optional property

.github/workflows/test.yml, package.json
This pr also includes workflows for code testing
=> feat: better esm support

src/connectors/libs/OceanicJS.ts, src/connectors/libs/index.ts
[Oceanic.js](https://npmjs/package/oceanic.js)
=> Support oceanic library

src/guild/Player.ts
See https://github.com/freyacodes/Lavalink/releases/tag/3.5.1 and https://github.com/freyacodes/Lavalink/pull/738
=> Added the ping property to the player data

README.md
I think this is correct.
**Old methods:**
- `shoukaku.joinChannel()`
- `player.setVolume()`
=> readme fixes: update methods

src/guild/Connection.ts, src/node/Node.ts, src/node/Rest.ts
Minor improvement
Added Rest.getLavalinkInfo() and his type
> https://github.com/lavalink-devs/Lavalink/blob/master/IMPLEMENTATION.md#get-lavalink-info
=> Enhancements

.gitignore, src/Shoukaku.ts, src/guild/Player.ts
I really feel that this would be a better event type control, and I feel that it would be much more convenient to add new events without having to write the 3 listeners.
Any changes or suggestions are welcome, even if you don't like the idea of this change.
=> Better type control + pnpm

src/guild/Player.ts
.playTrack() will not change the boolean value of .paused
=> Fix issue #175

src/Shoukaku.ts
Adds moveVoiceChannel, closes #199
=> feat: move voice channel function

package-lock.json, package.json, src/Constants.ts, src/Shoukaku.ts, src/connectors/Connector.ts, src/guild/Connection.ts, src/guild/Player.ts, src/node/Node.ts, src/node/Rest.ts
Allows for better validation of responses and enforces limits for numerical options on some options.
This introduces zod as a dependency.
Also improves some code documentation comments (supersedes #183).
=> feat: convert lavalink interface types to zod objects
